<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
<title>libs/base/src/base/guid.test.cc</title>
</head>
<body>
<h1>libs/base/src/base/guid.test.cc</h1>
<hr>
<h3>warning:  chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>libs/base/src/base/guid.test.cc 11 : 9</i></p>
<pre>
   11 |         CHECK(string_from(nil_guid) == "00000000-0000-0000-0000-000000000000");
      |         ^
</pre>
<p> expanded from macro 'CHECK'</p>
<p><i>external/catch2/src/catch2/catch_test_macros.hpp 132 : 24</i></p>
<pre>
  132 |   #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p> expanded from macro 'INTERNAL_CATCH_TEST'</p>
<p><i>external/catch2/src/catch2/internal/catch_test_macro_impl.hpp 52 : 47</i></p>
<pre>
   52 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p> operand 'v0' is here</p>
<p><i>libs/base/src/base/guid.test.cc 11 : 9</i></p>
<pre>
   11 |         CHECK(string_from(nil_guid) == "00000000-0000-0000-0000-000000000000");
      |         ^
</pre>
<p> expanded from macro 'CHECK'</p>
<p><i>external/catch2/src/catch2/catch_test_macros.hpp 132 : 24</i></p>
<pre>
  132 |   #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p> expanded from macro 'INTERNAL_CATCH_TEST'</p>
<p><i>external/catch2/src/catch2/internal/catch_test_macro_impl.hpp 52 : 47</i></p>
<pre>
   52 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p> operand 'v1' is here</p>
<p><i>libs/base/src/base/guid.test.cc 11 : 15</i></p>
<pre>
   11 |         CHECK(string_from(nil_guid) == "00000000-0000-0000-0000-000000000000");
      |               ^
</pre>
<p> expanded from macro 'CHECK'</p>
<p><i>external/catch2/src/catch2/catch_test_macros.hpp 132 : 99</i></p>
<pre>
  132 |   #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
      |                                                                                                   ^~~~~~~~~~~
</pre>
<p> expanded from macro 'INTERNAL_CATCH_TEST'</p>
<p><i>external/catch2/src/catch2/internal/catch_test_macro_impl.hpp 52 : 70</i></p>
<pre>
   52 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p> operand 'v2' is here</p>
<p><i>libs/base/src/base/guid.test.cc 11 : 40</i></p>
<pre>
   11 |         CHECK(string_from(nil_guid) == "00000000-0000-0000-0000-000000000000");
      |                                        ^
</pre>
<p> expanded from macro 'CHECK'</p>
<p><i>external/catch2/src/catch2/catch_test_macros.hpp 132 : 99</i></p>
<pre>
  132 |   #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
      |                                                                                                   ^~~~~~~~~~~
</pre>
<p> expanded from macro 'INTERNAL_CATCH_TEST'</p>
<p><i>external/catch2/src/catch2/internal/catch_test_macro_impl.hpp 52 : 70</i></p>
<pre>
   52 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning:  chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>libs/base/src/base/guid.test.cc 30 : 13</i></p>
<pre>
   30 |             CHECK(string_from(*parsed) == "123e4567-e89b-12d3-a456-426614174000");
      |             ^
</pre>
<p> expanded from macro 'CHECK'</p>
<p><i>external/catch2/src/catch2/catch_test_macros.hpp 132 : 24</i></p>
<pre>
  132 |   #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p> expanded from macro 'INTERNAL_CATCH_TEST'</p>
<p><i>external/catch2/src/catch2/internal/catch_test_macro_impl.hpp 52 : 47</i></p>
<pre>
   52 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p> operand 'v0' is here</p>
<p><i>libs/base/src/base/guid.test.cc 30 : 13</i></p>
<pre>
   30 |             CHECK(string_from(*parsed) == "123e4567-e89b-12d3-a456-426614174000");
      |             ^
</pre>
<p> expanded from macro 'CHECK'</p>
<p><i>external/catch2/src/catch2/catch_test_macros.hpp 132 : 24</i></p>
<pre>
  132 |   #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p> expanded from macro 'INTERNAL_CATCH_TEST'</p>
<p><i>external/catch2/src/catch2/internal/catch_test_macro_impl.hpp 52 : 47</i></p>
<pre>
   52 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p> operand 'v1' is here</p>
<p><i>libs/base/src/base/guid.test.cc 30 : 19</i></p>
<pre>
   30 |             CHECK(string_from(*parsed) == "123e4567-e89b-12d3-a456-426614174000");
      |                   ^
</pre>
<p> expanded from macro 'CHECK'</p>
<p><i>external/catch2/src/catch2/catch_test_macros.hpp 132 : 99</i></p>
<pre>
  132 |   #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
      |                                                                                                   ^~~~~~~~~~~
</pre>
<p> expanded from macro 'INTERNAL_CATCH_TEST'</p>
<p><i>external/catch2/src/catch2/internal/catch_test_macro_impl.hpp 52 : 70</i></p>
<pre>
   52 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p> operand 'v2' is here</p>
<p><i>libs/base/src/base/guid.test.cc 30 : 43</i></p>
<pre>
   30 |             CHECK(string_from(*parsed) == "123e4567-e89b-12d3-a456-426614174000");
      |                                           ^
</pre>
<p> expanded from macro 'CHECK'</p>
<p><i>external/catch2/src/catch2/catch_test_macros.hpp 132 : 99</i></p>
<pre>
  132 |   #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
      |                                                                                                   ^~~~~~~~~~~
</pre>
<p> expanded from macro 'INTERNAL_CATCH_TEST'</p>
<p><i>external/catch2/src/catch2/internal/catch_test_macro_impl.hpp 52 : 70</i></p>
<pre>
   52 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
</body>
</html>
